### ISSUE TITLE
Error dialing loggregator server: websocket: bad handshake.

### ISSUE THREAD

**Issue by charlesh001** [yudai/cf_nise_installer#106]
Warning: error tailing logs
Error dialing loggregator server: websocket: bad handshake.
Please ask your Cloud Foundry Operator to check the platform configuration (loggregator endpoint is wss://loggregator.dazyun.com:443).

The loggregator failed.

**Comment by navneetjo** [comment]
i am getting same issue.will you please tell me how's this issue will solve..??????
