### ISSUE TITLE
/home/cloud/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/core_ext.rb:30:in `err': golang (aa5f90f06ada376085414bfc0c56c8cd67abba9c) is corrupted in blobstore (id=b14ee9bc-88c8-4094-907a-957cfeb4a9b6) (Bosh::Cli::CliError)

### ISSUE THREAD

**Issue by hanxy** [yudai/cf_nise_installer#110]
/home/cloud/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/core_ext.rb:30:in `err': golang (aa5f90f06ada376085414bfc0c56c8cd67abba9c) is corrupted in blobstore (id=b14ee9bc-88c8-4094-907a-957cfeb4a9b6) (Bosh::Cli::CliError)

When i install cf_nise_installer,  I meet this problem

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
