### ISSUE TITLE
cf_nice_installer failed due to certificate verify failed

### ISSUE THREAD

**Issue by jainmanoj** [yudai/cf_nise_installer#111]
I am install building cloud-foundary Devbox on Single Server
My env. is Ubuntu 12.04 64bit
following instructions for installation in https://github.com/yudai/cf_nise_installer

Consistently got following errors or two separate installations -
So this is the genuine issue, which needs to be fixed.

If there is workaround provide that.
(BTW, I tried all the solutions related to this issue, NONE of them is solving the current issue)

+ sudo env PATH=/root/.rbenv/bin:/root/.rbenv/bin:/root/.rbenv/bin:/root/.rbenv/bin:/root/.rbenv/bin:/root/.rbenv/shims:/root/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games bundle exec ./bin/nise-bosh -y ../cf-release ../manifests/deploy.yml micro -n 10.9.17.182
The following templates and packages for job micro will be installed.
    # postgres
at depth 1 - 20: unable to get local issuer certificate
at depth 1 - 20: unable to get local issuer certificate
at depth 1 - 20: unable to get local issuer certificate
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:163:in `rescue in find_in_indices': Blobstore error: Failed to fetch object, underlying error: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed> /root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:300:in `connect' (Bosh::Cli::BlobstoreError)
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:300:in `ssl_connect'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:739:in `block in connect'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/timeout.rb:65:in `timeout'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/timeout.rb:96:in `timeout'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:731:in `connect'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:594:in `query'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient/session.rb:161:in `query'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:1060:in `do_get_block'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:869:in `block in do_request'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:956:in `protect_keep_alive_disconnected'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:868:in `do_request'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:756:in `request'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/httpclient-2.2.4/lib/httpclient.rb:661:in `get'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/simple_blobstore_client.rb:38:in `get_file'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/base.rb:50:in `get'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_common-1.2175.0/lib/common/retryable.rb:21:in `block in retryer'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `loop'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `retryer'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:150:in `find_in_indices'
/root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:117:in `find_job'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:300:in `find_job_template_archive'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:274:in `job_template_spec'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:284:in `job_template_packages'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:98:in `block in run_default_mode'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `each'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `run_default_mode'
/home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
./bin/nise-bosh:4:in `<main>'
        from /root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:121:in `find_in_indices'
        from /root/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:117:in `find_job'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:300:in `find_job_template_archive'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:274:in `job_template_spec'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:284:in `job_template_packages'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:98:in `block in run_default_mode'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `each'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `run_default_mode'
        from /home/MANOJ/CF/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
        from ./bin/nise-bosh:4:in `<main>'

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
