### ISSUE TITLE
Cannot use local CF server in Eclipse STS

### ISSUE THREAD

**Issue by constantin-ungureanu-github** [yudai/cf_nise_installer#112]
There is a certificate issue that prevents me to successfully add the local CF server to the Eclipse environment. There are several fields in the certificate that need to be filled (common name and DNS alternative name). Is there a way after the installation to replace this certificate?

![screenshot from 2014-08-26 12 35 48](https://cloud.githubusercontent.com/assets/8302329/4042781/1118d130-2d08-11e4-88da-1f1fc364c43e.png)
![screenshot from 2014-08-26 12 36 52](https://cloud.githubusercontent.com/assets/8302329/4042783/17c0707e-2d08-11e4-9818-cb1987e88739.png)

**Comment by constantin-ungureanu-github** [comment]
With latest updates for Eclipse STS Cloud Foundry plugin, it no longer accept self signed certificates, complaining that PKIX path building failed and then some exception.

To bypass this I had to import the our self signed certificate into Java trusted certificates, something like:
keytool -import -trustcacerts -keystore [PATH_TO_JAVA_JRE]/lib/security/cacerts -storepass changeit -noprompt -alias [SOME_ALIAS] -file [PATH_TO_CERT]

**Comment by yudai** [comment]
Thank you for the report.
This would help other people who use Eclipse.

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
