### ISSUE TITLE
can't install the right version of CF using cf_nise_installer

### ISSUE THREAD

**Issue by stepyu** [yudai/cf_nise_installer#113]
hi,
 I cloned the develop branch of CF which a little head of 176 version, while when I finished the installation using cf_nise_installer , the CF installed just seems to be 172 version of CF. does anyone can give me some tips.
thanks in advance! 

stepyu

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
