### ISSUE TITLE
Latest CF build with cf_nise_installer not working

### ISSUE THREAD

**Issue by yacovm** [yudai/cf_nise_installer#114]
I created a new VM with ubuntu 10.0.4:
root@abiel1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 10.04.4 LTS
Release:        10.04
Codename:       lucid

And executed bootstrap.sh.
The installation was successful, and all components can be brought up via monit.
However, the loggregator isn't working.
/var/vcap/sys/log/loggregator/loggregator.stdout.log reads: 
http://pastebin.com/6YfnyyUy

And it seems like I can't push a simple node.js app:
Staging log: http://pastebin.com/XAqDvCEm
C:\Users\yacovm\Desktop\nodetest>cf push nodetesttt -c "node app.js"
Creating app nodetesttt in org myorg / space myspace as admin...
OK

Creating route nodetesttt.172.20.0.1.xip.io...
OK

Binding nodetesttt.172.20.0.1.xip.io to nodetesttt...
OK

Uploading nodetesttt...
Uploading app files from: C:\Users\yacovm\Desktop\nodetest
Uploading 4.2M, 457 files
OK

Starting app nodetesttt in org myorg / space myspace as admin...
OK

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 down
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 failing
FAILED
Start unsuccessful

TIP: use 'cf logs nodetesttt --recent' for more information

This is the code of app.js:
var http = require('http');
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "html"});
  var data = "<HTML> <head><meta http-equiv=\"refresh\" content=\"1\"></head><body>";
  response.end("</body></html>");
});

// Listen on port 8000, IP defaults to 127.0.0.1
var port = process.env.VCAP_APP_PORT || parseInt(3000 + Math.random() * 100);
server.listen(port);

function log() {
        console.log("test");
        setTimeout(log,1000);
}

log();

and this is the package.json: 
{
  "name": "default-nodejs-app",
  "version": "0.0.1",
  "author": "Your Name",
  "dependencies": {
    "express": "3.4.8"
  },
  "engines": {
    "node": "0.10.x",
    "npm": "1.3.x"
  }
}

The same app can be successfully pushed to another CF server (after cf targetting the server):
http://pastebin.com/82MyrDe6

In the dea_next.log I found:
{"timestamp":1410179469.346716,"message":"instance.start.failed with error failed to accept connections within health check timeout","log_level":"warn","source":"Dea::Instance","data":{"attributes":{"prod":false,"executableFile":"deprecated","limits":{"mem":1024,"disk":1024,"fds":16384},"cc_partition":"default","console":false,"debug":null,"start_command":"node app.js","health_check_timeout":null,"vcap_application":{"limits":{"mem":1024,"disk":1024,"fds":16384},"application_version":"e422a754-e611-4a9e-9883-7468d6b773fb","application_name":"nodetesttt","application_uris":["nodetesttt.172.20.0.1.xip.io"],"version":"e422a754-e611-4a9e-9883-7468d6b773fb","name":"nodetesttt","space_name":"myspace","space_id":"c0fbdf32-f00a-40b2-bcaa-4f743205c9b2","uris":["nodetesttt.172.20.0.1.xip.io"],"users":null},"egress_network_rules":[{"protocol":"all","destination":"0.0.0.0-9.255.255.255"},{"protocol":"all","destination":"11.0.0.0-169.253.255.255"},{"protocol":"all","destination":"169.255.0.0-172.15.255.255"},{"protocol":"all","destination":"172.32.0.0-192.167.255.255"},{"protocol":"all","destination":"192.169.0.0-255.255.255.255"},{"protocol":"all","destination":"10.0.0.0-10.255.255.255"},{"protocol":"all","destination":"172.16.0.0-172.31.255.255"},{"protocol":"all","destination":"192.168.0.0-192.168.255.255"},{"protocol":"tcp","destination":"0.0.0.0/0","ports":"53"},{"protocol":"udp","destination":"0.0.0.0/0","ports":"53"}],"instance_index":0,"application_version":"e422a754-e611-4a9e-9883-7468d6b773fb","application_name":"nodetesttt","application_uris":["nodetesttt.172.20.0.1.xip.io"],"application_id":"a2f3ae3e-27c6-448e-9265-13e2ca6fe08b","droplet_sha1":"d0846848e5ba5fef87ad5cb3f8ee785f0db67f17","instance_id":"07f2ce4e747e49dc8b376e1eed80e154","private_instance_id":"52f1a298cbf4420ea5607579fbde42516cafbfc3e5fa49f789c8114b71468a3d","state":"CRASHED","state_timestamp":1410179469.3460753,"state_born_timestamp":1410179408.5510533,"state_starting_timestamp":1410179408.552164,"warden_handle":"182hiah00uh","warden_job_id":68,"state_crashed_timestamp":1410179469.3460784},"duration":60.794079838,"error":"failed to accept connections within health check timeout","backtrace":["/var/vcap/packages/dea_next/lib/dea/promise.rb:81:in `resolve'","/var/vcap/packages/dea_next/lib/dea/promise.rb:14:in `block in resolve'"]},"thread_id":12970120,"fiber_id":30845

I tailed the last lined from each hm9000 log and things look OK: 
{"timestamp":1410175772.940105915,"process_id":3620,"source":"vcap.hm9000.evacuator","log_level":"info","message":"Listening for DEA Evacuations","data":null}
{"timestamp":1410179654.098024130,"process_id":2387,"source":"vcap.hm9000.fetcher","log_level":"info","message":"Daemonize Time - {\"Component\":\"Fetcher\",\"Duration\":\"0.3129\"}","data":null}
{"timestamp":1410179694.423281670,"process_id":2341,"source":"vcap.hm9000.listener","log_level":"info","message":"Saved Heartbeats - {\"Duration\":\"2.77906ms\",\"Heartbeats to Save\":\"1\"}","data":null}
{"timestamp":1410175515.404896975,"process_id":2487,"source":"vcap.hm9000.metrics_server","log_level":"info","message":"Serving Metrics","data":null}
{"timestamp":1410179688.536826134,"process_id":3585,"source":"vcap.hm9000.sender","log_level":"info","message":"Daemonize Time - {\"Component\":\"Sender\",\"Duration\":\"0.0329\"}","data":null}
{"timestamp":1410179118.725620985,"process_id":2582,"source":"vcap.hm9000.shredder","log_level":"info","message":"Daemonize Time - {\"Component\":\"Shredder\",\"Duration\":\"0.0696\"}","data":null}
{"timestamp":1410179693.647804022,"process_id":2420,"source":"vcap.hm9000.analyzer","log_level":"info","message":"Daemonize Time - {\"Component\":\"Analyzer\",\"Duration\":\"0.0041\"}","data":null}
{"timestamp":1410179691.461760283,"process_id":2519,"source":"vcap.hm9000.api_server","log_level":"info","message":"Responded succesfully to app.state request - {\"elapsed time\":\"7.531598ms\",\"payload\":\"{\\\"droplet\\\":\\\"a2f3ae3e

and: 
{"timestamp":1410175772.940105915,"process_id":3620,"source":"vcap.hm9000.evacuator","log_level":"info","message":"Listening for DEA Evacuations","data":null}
{"timestamp":1410179714.432610273,"process_id":2387,"source":"vcap.hm9000.fetcher","log_level":"info","message":"Daemonize Time - {\"Component\":\"Fetcher\",\"Duration\":\"0.6473\"}","data":null}
{"timestamp":1410179724.423590899,"process_id":2341,"source":"vcap.hm9000.listener","log_level":"info","message":"Saved Heartbeats - {\"Duration\":\"4.144658ms\",\"Heartbeats to Save\":\"1\"}","data":null}
{"timestamp":1410175515.404896975,"process_id":2487,"source":"vcap.hm9000.metrics_server","log_level":"info","message":"Serving Metrics","data":null}
{"timestamp":1410179728.533340216,"process_id":3585,"source":"vcap.hm9000.sender","log_level":"info","message":"Daemonize Time - {\"Component\":\"Sender\",\"Duration\":\"0.0285\"}","data":null}
{"timestamp":1410179118.725620985,"process_id":2582,"source":"vcap.hm9000.shredder","log_level":"info","message":"Daemonize Time - {\"Component\":\"Shredder\",\"Duration\":\"0.0696\"}","data":null}

Is it possible that the new release is broken? 

Many thanks in advance.

**Comment by yacovm** [comment]
Hi.

Any news\updates?

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
