### ISSUE TITLE
I hava  deployed cloud foundry on ubuntu 14.04 STL several times, but it still has errors 

### ISSUE THREAD

**Issue by uttp** [yudai/cf_nise_installer#117]
Have someone can help me?Thanks a lot
#[31180] INFO: Running the packaging script for golang
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:163:in `rescue in find_in_indices': Blobstore error: Failed to fetch object, underlying error: #<HTTPClient::ConnectTimeoutError: execution expired> /home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `initialize' (Bosh::Cli::BlobstoreError)
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `new'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `create_socket'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:732:in `block in connect'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:731:in `connect'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:594:in `query'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:161:in `query'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:1060:in `do_get_block'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:869:in `block in do_request'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:956:in `protect_keep_alive_disconnected'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:868:in `do_request'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:756:in `request'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:661:in `get'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/simple_blobstore_client.rb:38:in `get_file'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/base.rb:50:in `get'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:21:in `block in retryer'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `loop'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `retryer'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:150:in `find_in_indices'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:109:in `find_package'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:306:in `find_package_archive'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/bosh.rb:251:in `get_source_package'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:62:in `start'
/home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:31:in `process'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:218:in `run_packaging'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:208:in `install_package'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:194:in `block in install_packages'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `each'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `install_packages'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:265:in `install_job'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:107:in `run_default_mode'
/home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
./bin/nise-bosh:4:in `<main>'
	from /home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:121:in `find_in_indices'
	from /home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:109:in `find_package'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:306:in `find_package_archive'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/bosh.rb:251:in `get_source_package'
	from /home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:62:in `start'
	from /home/uttp/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_agent-1.2175.0/lib/bosh_agent/message/compile_package.rb:31:in `process'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:218:in `run_packaging'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:208:in `install_package'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:194:in `block in install_packages'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `each'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:192:in `install_packages'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:265:in `install_job'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:107:in `run_default_mode'
	from /home/uttp/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
	from ./bin/nise-bosh:4:in `<main>'

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
