### ISSUE TITLE
cf_nise_installer issue - failed during install

### ISSUE THREAD

**Issue by chinhnguyen8855** [yudai/cf_nise_installer#119]
Hello,
I face the below error when install CF on both Ubuntu 10, Ubuntu 12.
Would you please shed some lights?

Chinh
.....
Using bundler 1.7.4
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
+ sudo env PATH=/home/i834373/.rbenv/shims:/home/i834373/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/ruby/bin/ bundle exec ./bin/nise-bosh -y ../cf-release ../manifests/deploy.yml micro -n 10.173.0.89
The following templates and packages for job micro will be installed.
    # postgres
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:163:in `rescue in find_in_indices': Blobstore error: Failed to fetch object, underlying error: #<SocketError: getaddrinfo: Name or service not known (https://s3.amazonaws.com:443)> /home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `initialize' (Bosh::Cli::BlobstoreError)
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `new'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:775:in `create_socket'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:732:in `block in connect'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:731:in `connect'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:594:in `query'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient/session.rb:161:in `query'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:1060:in `do_get_block'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:869:in `block in do_request'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:956:in `protect_keep_alive_disconnected'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:868:in `do_request'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:756:in `request'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/httpclient-2.2.4/lib/httpclient.rb:661:in `get'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/simple_blobstore_client.rb:38:in `get_file'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/s3_blobstore_client.rb:87:in `get_file'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/base.rb:50:in `get'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/sha1_verifiable_blobstore_client.rb:19:in `get'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:19:in `block in get'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:21:in `block in retryer'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `loop'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_common-1.2175.0/lib/common/retryable.rb:19:in `retryer'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/blobstore_client-1.2175.0/lib/blobstore_client/retryable_blobstore_client.rb:18:in `get'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:150:in `find_in_indices'
/home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:117:in `find_job'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:300:in `find_job_template_archive'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:274:in `job_template_spec'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:284:in `job_template_packages'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:98:in `block in run_default_mode'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `each'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `run_default_mode'
/home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
./bin/nise-bosh:4:in `<main>'
	from /home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:121:in `find_in_indices'
	from /home/i834373/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/bosh_cli-1.2175.0/lib/cli/release_compiler.rb:117:in `find_job'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:300:in `find_job_template_archive'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:274:in `job_template_spec'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/builder.rb:284:in `job_template_packages'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:98:in `block in run_default_mode'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `each'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:96:in `run_default_mode'
	from /home/i834373/cf_nise_installer/nise_bosh/lib/nise_bosh/runner.rb:70:in `run'
	from ./bin/nise-bosh:4:in `<main>'

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.

**Comment by Alex-toughman** [comment]
Hi 
I faced the same issue, it seems that session.rb:775   socket = TCPSocket.new(.....) need a parameters set the proxy server and proxy port. I'm not familiar with the RUBY, so I don't how to fix it.
do you have any idea?

**Comment by Alex-toughman** [comment]
BTW, I've already set the proxy variable in the ENV when  I run bootstrap.sh

**Comment by Alex-toughman** [comment]
It seems that we need to modify the install_cf_release.sh, add your proxy vairable after "env", then I can pass this point.
