### ISSUE TITLE
No services installed

### ISSUE THREAD

**Issue by PavelKovalets** [yudai/cf_nise_installer#12]
Hi, I've used cf_nise_installer to install Cloud Foundry V2 to Ubuntu Server 10.04. It was really cool and smooth experience,I've got my Controller running and was able to connect using CF tool. (There were no default spaces/domains installed so I had to create some to deploy simple node.js app - hope this is not an issue).

But when I've decided to run some services, I didn't found any of them. Running cf gave following

> cf create-service
> DL is deprecated, please use Fiddle
> Cannot find services matching the given criteria.

So I suppose there were no services installed. According to README I had to run  register_service_tokens.sh script to install those, but I could not find it in source (browsing the commit history showed that it was deleted).
So what can I do to have any service provisioned? And also it seems README file needs some updates.

**Comment by jabrena** [comment]
Hi, 

I am using this environment in local, running a Node.js app. My idea is to add a MySQL Service but if I execute cf m I didn't see any service.

How to add the Service to use mysql?
https://github.com/cloudfoundry/cf-mysql-broker

Many thanks in advance.

Juan Antonio

**Comment by yudai** [comment]
To add a new service broker, you need to modify the manifest file in this project. I highly recommend you use BOSH to deploy complicated environments like this. Try bosh-lite.
