### ISSUE TITLE
I can't start warden, anyone can help me?

### ISSUE THREAD

**Issue by zjucx** [yudai/cf_nise_installer#123]
Process 'nats'                      running
Process 'nats_stream_forwarder'     running
Process 'cloud_controller_ng'       running
Process 'cloud_controller_jobs_1'   running
Process 'cloud_controller_jobs_2'   running
Process 'nginx_ccng'                running
Process 'uaa'                       running
Process 'uaa_cf-registrar'          running
Process 'gorouter'                  running
Process 'warden'                    not monitored
Process 'dea_next'                  not monitored
Process 'dir_server'                running
Process 'etcd'                      running
Process 'hm9000_listener'           running
Process 'hm9000_fetcher'            running
Process 'hm9000_analyzer'           running
Process 'hm9000_sender'             running
Process 'hm9000_metrics_server'     running
Process 'hm9000_api_server'         running
Process 'hm9000_evacuator'          running
Process 'hm9000_shredder'           running
Process 'postgres'                  running
System 'system_ubuntu'              running

I donot know why. Please help me.

Here is the log in /var/vcap/sys/log/warden/warden.stderr.log:

rake aborted!
invalid byte sequence in US-ASCII

Tasks: TOP => warden:start
(See full trace by running task with --trace)

**Comment by yudai** [comment]
Something like `LANG=C` might work?

**Comment by df007** [comment]
Same problem to me in ubutnu 12.04,
Probably kernel issue.  Guess Warden still need ubuntu 10's file system to run?

{"timestamp":1425218683.5444398,"message":"Exited with status 1 (0.076s): [[\"/var/vcap/data/packages/warden/7d6d68c3f52d9a0925171f879e953b352bbf1325/warden/src/closefds/closefds\", \"/var/vcap/data/packages/warden/7d6d68c3f52d9a0925171f879e953b352bbf1325/warden/src/closefds/closefds\"], \"/var/vcap/data/packages/warden/7d6d68c3f52d9a0925171f879e953b352bbf1325/warden/root/linux/setup.sh\"]","log_level":"warn","source":"Warden::Container::Linux","data":{"stdout":" * Unloading AppArmor profiles\n * AppArmor not available as kernel LSM.\n   ...fail!\n","stderr":""},"thread_id":8558700,"fiber_id":17906980,"process_id":5503,"file":"/var/vcap/data/packages/warden/7d6d68c3f52d9a0925171f879e953b352bbf1325/warden/lib/warden/container/spawn.rb","lineno":135,"method":"set_deferred_success"}

**Comment by ozzozz** [comment]
I encountered same problem, and could fix by same hack as @df007 .
Using Ubuntu 12.04, and cf-release v207 bumped cf_nise_installer.
LANG environment value is not related.

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
