### ISSUE TITLE
I got  error "Failed setting memory limit: Permission denied - /tmp/warden/cgroup/memory/instance-18ensb4lmgh/memory.memsw.limit_in_bytes" on ubuntu-14.04.1-desktop

### ISSUE THREAD

**Issue by wligopivotal** [yudai/cf_nise_installer#124]
pivotal@ubuntu:~/app$ cf push hello -p ./HelloWorld.war 
Creating app hello in org DevBox / space test as admin...
OK

Creating route hello.192.168.177.135.xip.io...
OK

Binding hello.192.168.177.135.xip.io to hello...
OK

Uploading hello...
Uploading app files from: ./HelloWorld.war
Uploading 428.3K, 18 files
OK

Starting app hello in org DevBox / space test as admin...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: failed to stage application:
Failed setting memory limit: Permission denied - /tmp/warden/cgroup/memory/instance-18ensb4lmgh/memory.memsw.limit_in_bytes

pivotal@ubuntu:~/app$ cf apps
Getting apps in org DevBox / space test as admin...
OK

name    requested state   instances   memory   disk   urls   
hello   started           -1/1        1G       1G     hello.192.168.177.135.xip.io

**Comment by wdxxs2z** [comment]
sudo echo "GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"" >> /etc/default/grub sudo /usr/sbin/update-grub

reboot you compute.

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.

**Comment by Gary-Xie** [comment]
I met the same issue when I push a nodejs app into CF, my cf version is 210. It is my error log, please check it.

Uploading hwjs...
Uploading app files from: /home/gary/projects/HelloWorldByNodeJS
Uploading 19.7K, 13 files
Done uploading               
OK

Starting app hwjs in org icap / space icapspace as admin...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: failed to stage application:
Failed setting memory limit: Permission denied @ rb_sysopen - /tmp/warden/cgroup/memory/instance-194rv4okqrm/memory.memsw.limit_in_bytes

gary@ubuntu:~/projects/HelloWorldByNodeJS$

**Comment by wdxxs2z** [comment]
@Gary-Xie 
```
sudo echo "GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"" >> /etc/default/grub 
sudo /usr/sbin/update-grub
```
Then reboot.
