### ISSUE TITLE
cf_nise_installer failing to install on WIn 7 X64

### ISSUE THREAD

**Issue by balaramaraju** [yudai/cf_nise_installer#129]
I tried to setup cf in my local system [win 7] 
steps that I did :- 
1. git clone https://github.com/yudai/cf_nise_installer/
2 install vagrant for windows [Vagrant 1.7.2]
3 started vagrant for that folder "Vagrant up"

it is failing with 

: invalid option
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Logs :-1: 

D:\Cloud\Git\cf_nise_installer>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'trusty64' (v0) for provider: virtualbox
    default: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
    default: Progress: 100% (Rate: 761k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'trusty64' (v0) for 'virtualbox'!
==> default: Importing base box 'trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: cf_nise_installer_default_1432029164724_88542
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/Cloud/Git/cf_nise_installer
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Ign http://security.ubuntu.com trusty-security InRelease
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
==> default: Ign http://archive.ubuntu.com trusty-updates InRelease
==> default: Get:2 http://security.ubuntu.com trusty-security Release [63.5 kB]
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Get:3 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Get:4 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
==> default: Get:5 http://security.ubuntu.com trusty-security/main Sources [80.6 kB]
==> default: Get:6 http://security.ubuntu.com trusty-security/universe Sources [24.9 kB]
==> default: Get:7 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
==> default: Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [268 kB]
==> default: Get:9 http://security.ubuntu.com trusty-security/universe amd64 Packages [103 kB]
==> default: Hit http://security.ubuntu.com trusty-security/main Translation-en
==> default: Hit http://security.ubuntu.com trusty-security/universe Translation-en
==> default: Get:10 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Get:11 http://archive.ubuntu.com trusty-updates/main Sources [202 kB]
==> default: Get:12 http://archive.ubuntu.com trusty-updates/universe Sources [117 kB]
==> default: Get:13 http://archive.ubuntu.com trusty-updates/main amd64 Packages [517 kB]
==> default: Get:14 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [279 kB]
==> default: Hit http://archive.ubuntu.com trusty-updates/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 9,183 kB in 44s (206 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   python-software-properties
==> default: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
==> default: Need to get 19.6 kB of archives.
==> default: After this operation, 138 kB of additional disk space will be used.
==> default: Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe python-software-properties all 0.92.37.3 [19.6 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 19.6 kB in 1s (19.5 kB/s)
==> default: Selecting previously unselected package python-software-properties.
==> default: (Reading database ... 60975 files and directories currently installed.)
==> default: Preparing to unpack .../python-software-properties_0.92.37.3_all.deb ...
==> default: Unpacking python-software-properties (0.92.37.3) ...
==> default: Setting up python-software-properties (0.92.37.3) ...
==> default:  The most current stable version of Git for Ubuntu.
==> default:
==> default: For release candidates, go to https://launchpad.net/~git-core/+archive/candidate .
==> default:  More info: https://launchpad.net/~git-core/+archive/ubuntu/ppa
==> default: gpg:
==> default: keyring `/tmp/tmpwz4erq00/secring.gpg' created
==> default: gpg:
==> default: keyring `/tmp/tmpwz4erq00/pubring.gpg' created
==> default: gpg:
==> default: requesting key E1DF1F24 from hkp server keyserver.ubuntu.com
==> default: gpg:
==> default: /tmp/tmpwz4erq00/trustdb.gpg: trustdb created
==> default: gpg:
==> default: key E1DF1F24: public key "Launchpad PPA for Ubuntu Git Maintainers" imported
==> default: gpg:
==> default: Total number processed: 1
==> default: gpg:
==> default:               imported: 1
==> default:   (RSA: 1)
==> default: OK
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: /bin/bash:
: invalid option
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

D:\Cloud\Git\cf_nise_installer>

please let us know what went wrong.

**Comment by yudai** [comment]
It seems Vagrant failed at https://github.com/yudai/cf_nise_installer/blob/0870664b6c954606a318024791ba9e6bb22c5d15/Vagrantfile#L22

If recreating your box doesn't solve the problem, you can SSH into your box (with `vagrant ssh`) and manually run the installer script in it. The command to be run is written in the link above.

**Comment by balaramaraju** [comment]
Yes, I tried to execute manually but while executing ./scripts/install_cf_release.sh it is keep hanging at running the packaging scripts for buildpack_java_offline.
Using rake 10.3.2
Using json 1.8.1
Using nokogiri 1.5.11
Using uuidtools 2.1.4
Using aws-sdk 1.32.0
Using bcrypt-ruby 3.0.1
Using beefcake 0.3.7
Using semi_semantic 1.1.0
Using bosh_common 1.2611.0
Using builder 3.1.4
Using excon 0.25.3
Using formatador 0.2.5
Using mime-types 2.3
Using multi_json 1.10.1
Using net-ssh 2.9.1
Using net-scp 1.1.2
Using ruby-hmac 0.4.0
Using fog 1.14.0
Using httpclient 2.2.4
Using log4r 1.1.10
Using ruby-atmos-pure 1.0.5
Using blobstore_client 1.2611.0
Using gibberish 1.2.2
Using yajl-ruby 1.1.0
Using bosh-core 1.2611.0
Using bosh-director-core 1.2611.0
Using sequel 3.43.0
Using rack 1.5.2
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using daemons 1.1.9
Using eventmachine 1.0.3
Using thin 1.5.1
Using bosh-registry 1.2611.0
Using bosh_cpi 1.2611.0
Using bosh_aws_cpi 1.2611.0
Using bosh_openstack_cpi 1.2611.0
Using rest-client 1.6.7
Using bosh_vcloud_cpi 0.5.4
Using membrane 0.0.5
Using mysql2 0.3.16
Using pg 0.15.1
Using bosh_vsphere_cpi 1.2611.0
Using warden-protocol 0.1.4
Using warden-client 0.1.0
Using bosh_warden_cpi 1.2611.0
Using json_pure 1.8.1
Using nats 0.5.0.beta.12
Using netaddr 1.5.0
Using rack-test 0.6.2
Using redis 3.0.7
Using redis-namespace 1.4.1
Using vegas 0.1.11
Using resque 1.23.1
Using resque-backtrace 0.0.1
Using thread_safe 0.3.4
Using tzinfo 1.2.1
Using rufus-scheduler 2.0.24
Using ffi 1.9.3
Using sys-filesystem 1.1.2
Using bosh-director 1.2611.0
Using bosh-stemcell 1.2611.0
Using crack 0.3.2
Using sigar 0.7.2
Using syslog_protocol 0.9.2
Using bosh_agent 1.2611.0
Using highline 1.6.21
Using minitar 0.5.4
Using net-ssh-gateway 1.2.0
Using progressbar 0.9.2
Using terminal-table 1.4.5
Using bosh_cli 1.2611.0
Using diff-lcs 1.2.5
Using rspec-support 3.0.2
Using rspec-core 3.0.2
Using rspec-expectations 3.0.2
Using rspec-mocks 3.0.2
Using rspec 3.0.0
Using bundler 1.9.9
Bundle complete! 8 Gemfile dependencies, 80 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
The following templates and packages for job micro will be installed.
    # postgres
        * common
        * postgres
#[2741] INFO: Resolving package dependencies...
#[2741] INFO: Installing the following packages:
#[2741] INFO:  * common
#[2741] INFO:  * postgres
#[2741] INFO: Installing package common
#[2741] INFO: The same version of the package is already installed. Skipping
#[2741] INFO: Installing package postgres
#[2741] INFO: The same version of the package is already installed. Skipping
Done!
The following templates and packages for job micro_ng will be installed.
    # nats
        * common
        * gnatsd
    # nats_stream_forwarder
        * common
        * ruby-2.1.4
        * nats
    # etcd
        * common
        * etcd
    # hm9000
        * common
        * hm9000
    # cloud_controller_ng
        * common
        * cloud_controller_ng
        * nginx
        * nginx_newrelic_plugin
        * libpq
        * mysqlclient
        * ruby-2.1.4
        * buildpack_java
        * buildpack_java_offline
        * buildpack_ruby
        * buildpack_nodejs
        * buildpack_go
        * buildpack_python
        * buildpack_php
    # cloud_controller_worker
        * common
        * cloud_controller_ng
        * nginx
        * nginx_newrelic_plugin
        * libpq
        * mysqlclient
        * ruby-2.1.4
    # cloud_controller_clock
        * common
        * cloud_controller_ng
        * nginx
        * nginx_newrelic_plugin
        * libpq
        * mysqlclient
        * ruby-2.1.4
    # uaa
        * common
        * ruby-2.1.4
        * uaa
    # haproxy
        * haproxy
    # gorouter
        * common
        * gorouter
    # dea_next
        * common
        * dea_next
        * warden
        * rootfs_lucid64
        * rootfs_cflinuxfs2
        * ruby-2.1.4
    # loggregator_trafficcontroller
        * common
        * loggregator_trafficcontroller
    # doppler
        * common
        * doppler
    # metron_agent
        * common
        * metron_agent
    # dea_logging_agent
        * common
        * dea_logging_agent
    # etcd_metrics_server
        * common
        * etcd_metrics_server
#[2821] INFO: Resolving package dependencies...
#[2821] INFO: Installing the following packages:
#[2821] INFO:  * common
#[2821] INFO:  * golang1.3
#[2821] INFO:  * gnatsd
#[2821] INFO:  * ruby-2.1.4
#[2821] INFO:  * nats
#[2821] INFO:  * etcd
#[2821] INFO:  * golang1.4
#[2821] INFO:  * hm9000
#[2821] INFO:  * libpq
#[2821] INFO:  * mysqlclient
#[2821] INFO:  * cloud_controller_ng
#[2821] INFO:  * nginx
#[2821] INFO:  * nginx_newrelic_plugin
#[2821] INFO:  * buildpack_java
#[2821] INFO:  * buildpack_java_offline
#[2821] INFO:  * buildpack_ruby
#[2821] INFO:  * buildpack_nodejs
#[2821] INFO:  * buildpack_go
#[2821] INFO:  * buildpack_python
#[2821] INFO:  * buildpack_php
#[2821] INFO:  * uaa
#[2821] INFO:  * haproxy
#[2821] INFO:  * gorouter
#[2821] INFO:  * dea_next
#[2821] INFO:  * warden
#[2821] INFO:  * rootfs_lucid64
#[2821] INFO:  * rootfs_cflinuxfs2
#[2821] INFO:  * loggregator_trafficcontroller
#[2821] INFO:  * doppler
#[2821] INFO:  * metron_agent
#[2821] INFO:  * dea_logging_agent
#[2821] INFO:  * etcd_metrics_server
#[2821] INFO: Installing package common
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package golang1.3
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package gnatsd
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package ruby-2.1.4
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package nats
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package etcd
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package golang1.4
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package hm9000
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package libpq
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package mysqlclient
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package cloud_controller_ng
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package nginx
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package nginx_newrelic_plugin
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package buildpack_java
#[2821] INFO: The same version of the package is already installed. Skipping
#[2821] INFO: Installing package buildpack_java_offline
#[2821] INFO: Running the packaging script for buildpack_java_offline

**Comment by yudai** [comment]
the Java Buildpack is so big and it takes much time especially when the network is slow.

**Comment by balaramaraju** [comment]
Thanks for info. It took me for 8 hrs to complete installation .
after i start the cf using ./scripts/start.sh i go below summary.

Logs :-1: 

All processes have been started!
 -u admin -p c1oudc0w --skip-ssl-validation'ip.io
Download CF CLI from https://github.com/cloudfoundry/cli

but i where can i find the api  endpoint details ? what is 'ip.io ?

**Comment by balaramaraju** [comment]
got the details
