### ISSUE TITLE
Process 'cloud_controller_ng'   not monitored

### ISSUE THREAD

**Issue by rishigits** [yudai/cf_nise_installer#130]
Hello - i am trying to install CF on RHEL using cf_nise_installer and most of the components show "running" except these:

Process 'cloud_controller_ng'       not monitored
Process 'cloud_controller_worker_local_1' not monitored
Process 'cloud_controller_worker_local_2' not monitored
Process 'nginx_cc'                  not monitored
Process 'cloud_controller_worker_1' Does not exist
Process 'cloud_controller_clock'    Does not exist

I tried to manually execute:

"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/console /var/vcap/jobs/cloud_controller_clock/config/cloud_controller_ng.yml"

But got this error:

/======================================================/
(0.000105s) SET standard_conforming_strings = ON
(0.000040s) SET client_min_messages = 'WARNING'
(0.000024s) SET DateStyle = 'ISO'
(0.000378s) SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
(0.000050s) SELECT * FROM "schema_migrations" LIMIT 1
(0.000244s) SELECT "filename" FROM "schema_migrations" ORDER BY "filename"
PG::UndefinedTable: ERROR:  relation "services" does not exist
LINE 1: ..."."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"services...
                                                             ^: SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"services"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
PG::UndefinedTable: ERROR:  relation "services" does not exist
LINE 1: SELECT * FROM "services" LIMIT 1
                      ^: SELECT * FROM "services" LIMIT 1
/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/2.1.0/gems/sequel-4.21.0/lib/sequel/extensions/migration.rb:368:in `check_current': migrator is not current (Sequel::Migrator::NotCurrentError)
        from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/db_migrator.rb:29:in `check_migrations!'
        from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/db.rb:52:in `load_models'
        from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/console.rb:28:in `<top (required)>'
        from /var/vcap/packages/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/vcap/packages/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /var/vcap/packages/cloud_controller_ng/cloud_controller_ng/bin/console:6:in `<main>'

/======================================================/

Please let me know if you spot anything obvious here - seems like "services" entry in not in a table.

Thanks.

**Comment by yudai** [comment]
Unfortunately, RHEL is not supported at this moment.

**Comment by rishigits** [comment]
Thanks Yudai.  I understand this is my own battle to fight but would you know if there is a way to recreate all the tables in Postgres (apart form reinstalling everything). Thanks.
