### ISSUE TITLE
When specifying NISE_DOMAIN, CF still recreates a self-signed Cert associated with XIP.IO

### ISSUE THREAD

**Issue by KevinHeathHigh** [yudai/cf_nise_installer#131]
Attempting to build out an internal dev box with `no` internet access.  I specify a NISE_DOMAIN so I can control the DNS.   Which works just fine, but when I attempt to deploy an app using the CF Java Client with trust self-signed = true option.  I get 

```
PaaS unavailable while deploying [revision=1,ex=org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.cf-dev.redacted.com/info":hostname in certificate didn't match: <api.cf-dev.redacted.com> != <*.10.xxx.xxx.xxx.xip.io>; nested exception is javax.net.ssl.SSLException: hostname in certificate didn't match: <api.cf-dev.redacted.com> != <*.10.xxx.xxx.xxx.xip.io>]
Jun 29 19:06:30.616 WARN   ///06d888d9-2e09-43d4-8b80-2579afd6b755/1/[] [http-0.0.0.0-8080-exec-11] #HTTP#@T: java.lang.IllegalStateException: Response.getWriter.ise
	 at com.redacted.server.http.message.HttpResponseImpl.getWriter(HttpResponseImpl.java:244)}}

```

Any chance to get the NISE_DOMAIN variable to pass on to the self-signed cert?

**Comment by KevinHeathHigh** [comment]
Ok, I redid my environment with an xip.io address and it appears that it is specifically with *.10.39.39.39.xip.io.  I had redacted this above thinking it was my local IP but my local is actually different.  It also appears we only see this with the Java Client and no the GO CLI.  So not sure if this is something in your install, or something your install has control over.

**Comment by KevinHeathHigh** [comment]
Looks like this is the same as issue #112

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
