### ISSUE TITLE
Is there any method to start CloudFoundry without reboot VM after deploying

### ISSUE THREAD

**Issue by jiangchuan1220** [yudai/cf_nise_installer#134]
After deploying CF with the command, I must reboot before starting, otherwise the start will fail. 
My question is why I must reboot after deploying? Is there any method to avoid reboot before deploying?

Thanks!

**Comment by jabrena** [comment]
Hi, I am using the installer too and If I understood you, you have to reboot your system after any deploymet process. In my case when I deploy with cf push, I don't have to reboot the VM with Cloud Foundry installed.

Is it correct your problem?

Juan Antonio

**Comment by yudai** [comment]
It's to reload the kernel. The latest kernel might not need rebooting (as it might already include required something). But I've not tested yet.

**Comment by yudai** [comment]
I tried with the latest kernel but still it fails to start the warden process. So rebooting is mandatory for now.

**Comment by yudai** [comment]
@jiangchuan1220 if you need to avoid the reboot, you can install `linux-image-virtual` and `linux-image-extra-virtual` with `apt-get install` before running the command. You may want to create a custom OS image with these apt packages.

**Comment by jiangchuan1220** [comment]
@yudai  Thanks for your reply and I will try the method. I do not want to reboot because I am deploying CF on aws ec2. I do not want to assign elastic ip to the ec2, so  once I reboot the ec2 instance, its public ip is changed and CF can not work well.

**Comment by jiangchuan1220** [comment]
@jabrena Thanks for your reply. I mean after I deploy CloudFoundry, I must reboot the system before I start cloudfoundry. 
The problem is because I am using aws ec2, once I reboot the system the public ip will change(I do not want to assign elastic ip). Then, CF can not start successfully because ip has changed.

**Comment by jiangchuan1220** [comment]
Hi yudai,
I installed linux-image-virtual and linux-image-extra-virtual with apt-get install and reboot, then I install CF using the command:
bash < <(curl -s -k -B https://raw.githubusercontent.com/yudai/cf_nise_installer/${INSTALLER_BRANCH:-master}/scripts/bootstrap.sh)

When the installation is completed, I start CF without rebooting, but the start failed. As is shown in the figure. @yudai 

My linux version is Ubuntu Server 14.04 LTS (HVM), SSD Volume Type. Do you have any idea to fix the problem? I will also try another methods to deploy without reboot.

![1](https://cloud.githubusercontent.com/assets/8613170/9079266/e870f1d6-3b7a-11e5-845a-b1cf18b9947d.png)

**Comment by yudai** [comment]
@jiangchuan1220 Thanks for the report. Indeed, your CF is working properly. However, the script now has a bug that cannot handle `accessible` files properly. I'll fix it when I have time, but for now, you can just ignore `File'haproxy_config'`.

**Comment by yudai** [comment]
@jiangchuan1220 Fixed the problem with accessible files.
