### ISSUE TITLE
CF nise & port forwarding

### ISSUE THREAD

**Issue by yacovm** [yudai/cf_nise_installer#136]
Hi.

If I have a nise bosh CF installation running on a server with an ip address of X, (which means the scripts install all components to listen to X, and the domain is X.xip.io,

I want to access the server (for example, with cf cli, etc.) with an external ip address of Y (and let's assume I have a port forwarding rule)

How do I make CF accept requests with destination of Y.xip.io instead of X.ip.io?

**Comment by yudai** [comment]
Provide the `NISE_DOMAIN`  environment variable.

```sh
export NISE_DOMAIN=Y.xip.io
./scripts/install.sh
```

**Comment by yudai** [comment]
Closing as it looks an outdated ticket. Please recreate another ticket when still you have the issue.
