### ISSUE TITLE
How to update the certificate on CF?

### ISSUE THREAD

**Issue by jabrena** [yudai/cf_nise_installer#141]
Hi,

am testing the instalation to test a https connection and I would like to know where is located this certificate:

```
Organization: Arielworks
Organization unit: Third Development Group
State / Province: Tokyo
Locality: Shinjuku
Country: JP
```

**Comment by yudai** [comment]
Hi @jabrena,
I think the cert file is included in the manifest template file.
You can replace those lines to update the SSL certificate of your endpoint.
https://github.com/yudai/cf_nise_installer/blob/master/manifests/template.yml#L318-L367
