### ISSUE TITLE
Can not use Eclipse Cloud Foundry Plugin to log in CF installed by this installer

### ISSUE THREAD

**Issue by jinsenglin** [yudai/cf_nise_installer#142]
After CF installation with this installer, I can use `cf` command line to log in and push app to the CF. However I can't use Eclipse Cloud Foundry Plugin to log in the CF. The error message says: "Wrong email or password - 403 (Forbidden) - 403 Error requesting access token."

Is this a known issue? how do I diagnose this issue?

Here is the account information
Email: admin
Password: c1oudc0w
URL: http://api.140.92.25.12.xip.io

Thanks a lot.

**Comment by yudai** [comment]
Looks like, you gave a wrong username or password to the plugin?

**Comment by jinsenglin** [comment]
I think it is the same issue as this https://github.com/yudai/cf_nise_installer/issues/95
