### ISSUE TITLE
unable to access api endpoint

### ISSUE THREAD

**Issue by suryaveerc** [yudai/cf_nise_installer#146]
I have installed a local cloud foundry instance following the steps

Environment:

Host: Windows 10
Vagrant: 1.7.4
Virtualbox: 5.0.2
cf: 6.13.0-e68ce0f-2015-10-15T15:53:50+00:00
Installation went fine but when I try to access the endpoint using the command:

cf login -a https://api.10.0.2.15.xip.io -u admin -p c1oudc0w --skip-ssl-validation
I get following error

API endpoint: https://api.10.0.2.15.xip.io
FAILED 
Error performing request: Get https://api.10.0.2.15.xip.io/v2/info: dial tcp
10.0.2.15:443: ConnectEx tcp: i/o timeout
I googled and found it be some DNS and /etc/hosts entries issue so I changed the DNS of my wifi adapter to 8.8.8.8 / 8.8.4.4 and added following entries to the /etc/hosts file

10.0.2.15 api.10.0.2.15.xip.io
10.0.2.15 uaa.10.0.2.15.xip.io
10.0.2.15 10.0.2.15.xip.io
10.0.2.15 hello.10.0.2.15.xip.io

The hosts solution I got from issue #79 
I flushed the DNS, restarted but still I am getting same error.

Below is the output of nslookup api.10.0.2.15.xip.io

Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    api.10.0.2.15.xip.io
Address:  10.0.2.15
Now I am out of options. Please guide me what I am missing.

Thanks

**Comment by jabrena** [comment]
Take a look this discussion:
https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/HLIK46WQLCZAMJKJKVJNQLPZPZRO6SYZ/

**Comment by suryaveerc** [comment]
Thanks. I am sorry but I didn't understand what to do, pretty new to cloud foundry and vagrant. Would you mind explaining a bit.

**Comment by jabrena** [comment]
I have the same problem. I am working on it.
If I have some progress, I will inform you.

cheers

**Comment by suryaveerc** [comment]
Thanks.
I hope you solve it. I am trying too.

**Comment by suryaveerc** [comment]
I am able to resolve it.
I saw in the routing table there was no entry for 10.0.2.15. I added an entry for this as:
add route 10.0.2.15 10.39.39.1(this is VirtualBox host only adapter ip.)

This resolved the issue.

**Comment by jabrena** [comment]
@suryaveerc 

Good morning, did you add the line:

``` bash
route add 10.0.2.15 10.39.39.1
```

In the host where you have cf_nise_installer?

**Comment by suryaveerc** [comment]
@jabrena Hey Juan, Good Morning. 

Yes, I have done it on the host machine.

Merry Christmas.
