### ISSUE TITLE
Can we change the package source?

### ISSUE THREAD

**Issue by IMBlues** [yudai/cf_nise_installer#158]
I can never install the package postgres-9.4.6 for the network issue,and I try to use VPN to improve but help little.

So I wonder if there is a way to change the package source,because of the HORRIBLE network in China.
Any help will be appreciated!

**Comment by IMBlues** [comment]
I tried at least 10 times ,and finally passed......

**Comment by imlinhao** [comment]
使用迅雷下载s3资源到本地，然后修改源码从本机加载
