### ISSUE TITLE
bosh target throws an error

### ISSUE THREAD

**Issue by gowrisankar22** [yudai/cf_nise_installer#167]
Hi ,
when i set the target to bosh it throws error as below, can some one help ?
i307955@mo-eb106185c:~/cf_nise_installer/nise_bosh$ bosh vms --details
Please choose target first
i307955@mo-eb106185c:~/cf_nise_installer/nise_bosh$ bosh target https://api.10.97.156.146.xip.io
[WARNING] cannot access director, trying 4 more times...
[WARNING] cannot access director, trying 3 more times...
[WARNING] cannot access director, trying 2 more times...
[WARNING] cannot access director, trying 1 more times...
cannot access director (Connection refused - connect(2) (https://10.97.156.146:25555))

BRs, Gowrisanakr

**Comment by yudai** [comment]
This installer doesn't launch a BOSH cluster. It just install a CF cluster using the BOSH artifacts in cf-release. Therefore, it doesn't provide a BOSH endpoint.
