### ISSUE TITLE
Target refused connection.

### ISSUE THREAD

**Issue by levenaux** [yudai/cf_nise_installer#79]
Hello,

After running vagrant up I get this error:

vagrant@lucid64:/vagrant$ cf target http://api.10.0.2.15.xip.io
Setting target to http://api.10.0.2.15.xip.io... FAILED
Target refused connection.

If I add api.10.0.2.15.xip.io to the hosts file then it works. Any apps that I create will have to be added to the hosts files. I'm not sure this is an error on my side or on the code.

Regards,
Jamie

**Comment by jabrena** [comment]
Good morning @yudai,

does exist some way to change host names: xip.io to another better host name?

Juan Antonio
