### ISSUE TITLE
Unable to add NISE CF as a server in Eclipse via CF Plugin

### ISSUE THREAD

**Issue by kjhawar** [yudai/cf_nise_installer#95]
I want add my private CF NISE cloud as a server in the Eclipse IDE via the CloudFoundry Plugin.

My CF NISE setup is on virtualbox.

Initially, there were SSL exceptions (due to expired hard coded certificate in the code base and incorrect CN). i replaced the certificates with CN = api.10.39.39.39.xip.io.

the URL provided is "https://api.10.39.39.39.xip.io".
It needs email address and password to validate the account.
i have tried admin/c1oudc0w and vagrant/vagrant but its unable to validate
![eclipse1](https://cloud.githubusercontent.com/assets/7638096/3027835/895e37e0-e026-11e3-8a52-c580f5843561.PNG)

What credentials does this plugin expect for a CF NISE setup?

**Comment by cloudecho** [comment]
Hi @yudai ,
I have got the folling problem when creating a new server using eclipe plugin :
 Unable to communicate with server - I/O error on GET request for "https://api.cf.cloud/info": hostname in certificate didn't match: <api.cf.cloud> != <*.10.39.39.39.xip.io>; nested exception is javax.net.ssl.SSLException: hostname in certificate didn't match: <api.cf.cloud> != <*.10.39.39.39.xip.io>

cf.cloud is the hostname in my vitualbox.
Coud you tell me how  to solve this? Thx.

**Comment by cloudecho** [comment]
I have found a way to solve it:
Step1: Generate a self-signed certificate :
$ openssl genrsa 2048 > host.key 
$ openssl req -new -x509 -nodes -sha1 -days 3650 -key host.key > host.cert 
 #[enter *.cf.cloud (*.domain.com) for the Common Name] 
$ openssl x509 -noout -fingerprint -text < host.cert > host.info 
$ cat host.cert host.key > host.pem 
$ chmod 400 host.key host.pem 

Step2: Replace the haproxy/cert.pem with host.pem
​$ sudo find /var/vcap -name cert.perm
$ sudo cp host.pem /var/vcap/data/jobs/haproxy/....../config/cert.pem

Step3: Update to the CF nightly build through the Eclipse Help
see: http://dist.springsource.com/snapshot/TOOLS/cloudfoundry/nightly

Step4: Import the host.cert on the client host using keytool (a command tool) 
$ pwd
/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/jre/lib/security/_imports
$ sudo keytool -import -v -trustcacerts -alias microcf -file host.cert -keystore ../cacerts 
(default password: changeit)
$ keytool -list  -keystore ../cacerts  |grep microcf
microcf, 2015-1-23, trustedCertEntry,
